title: Zephyr中文网
subtitle: "Zephyr OS 中文网站"
description: "Zephyr Project, a IoT RTOS"
author: tidyjiang@163.com
language: zh-cn
timezone: UTC

url: https://hexo.io
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: navy
deploy:
  type: git
  repo:
    github: git@github.com:tidyjiang8/tidyjiang8.github.io.git,master

highlight:
  enable: true
  line_number: false

disqus_shortname: hexojs
google_analytics: UA-48498357-3
fb_admins: 100000247608790
algolia:
  en:
    api_key: c3d5d4c995b5e0c2ffb5623900279a66
    index_name: hexo
  zh-tw:
    api_key: c83d2ec3440f40aec6d0e695ecec7ef3
    index_name: hexo_zh-tw
  zh-cn:
    api_key: cdea7d4e47d84f6145b77e7f68689f35
    index_name: hexo_zh-cn
twitter: zephyriot
weibo: zephyrproject
github: zephyrproject-rtos/zephyr
